import { Activity, AlertTriangle, CheckCircle2, ChevronRight, CircleHelp, Clock3, LoaderCircle, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { historyApi } from '../../api/history';
import { Badge } from '../common/Badge';
import type { RunFlowEvent, RunFlowNode, RunFlowSnapshot, RunFlowStatus } from '../../types/analysis';

const STATUS: Record<RunFlowStatus, { label: string; className: string; Icon: typeof CheckCircle2; badge: 'default' | 'success' | 'warning' | 'danger' | 'info' }> = {
  pending: { label: '等待中', className: 'text-muted-text', Icon: CircleHelp, badge: 'default' }, running: { label: '运行中', className: 'text-primary', Icon: LoaderCircle, badge: 'info' }, success: { label: '完成', className: 'text-emerald-600', Icon: CheckCircle2, badge: 'success' }, failed: { label: '失败', className: 'text-red-600', Icon: XCircle, badge: 'danger' }, degraded: { label: '信息不足', className: 'text-amber-600', Icon: AlertTriangle, badge: 'warning' }, fallback: { label: '已降级', className: 'text-amber-600', Icon: AlertTriangle, badge: 'warning' }, skipped: { label: '跳过', className: 'text-muted-text', Icon: CircleHelp, badge: 'default' }, unknown: { label: '未记录', className: 'text-muted-text', Icon: CircleHelp, badge: 'default' },
};
const EVENT_FILTERS = ['all', 'warning', 'danger'] as const;
type EventFilter = typeof EVENT_FILTERS[number];

function FlowNode({ node, selected, onSelect }: { node: RunFlowNode; selected: boolean; onSelect: (node: RunFlowNode) => void }) {
  const status = STATUS[node.status]; const { Icon } = status;
  return <button type="button" onClick={() => onSelect(node)} aria-pressed={selected} className={`group flex w-full items-start gap-2 rounded-md border px-2.5 py-2 text-left transition-colors ${selected ? 'border-primary/60 bg-primary/10' : 'border-subtle bg-surface/65 hover:bg-hover'}`}><Icon className={`mt-0.5 h-4 w-4 shrink-0 ${status.className}`} aria-hidden="true" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-foreground">{node.label}</span><span className="mt-0.5 block truncate text-xs text-secondary-text">{node.provider || node.kind}</span></span><ChevronRight className="mt-0.5 h-4 w-4 shrink-0 text-muted-text" aria-hidden="true" /></button>;
}

function NodeDetails({ node }: { node: RunFlowNode | null }) {
  if (!node) return <div className="flex min-h-36 items-center justify-center text-center text-xs text-muted-text">选择一个节点查看执行详情</div>;
  const status = STATUS[node.status]; const entries = Object.entries(node.metadata || {}).filter(([, value]) => value !== null && value !== undefined && value !== '');
  return <div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-medium text-foreground">{node.label}</span><Badge variant={status.badge}>{status.label}</Badge></div><dl className="space-y-2 text-xs"><div className="flex justify-between gap-3"><dt className="text-muted-text">类型</dt><dd className="text-right text-secondary-text">{node.kind}</dd></div>{node.provider ? <div className="flex justify-between gap-3"><dt className="text-muted-text">来源</dt><dd className="max-w-[65%] truncate text-right text-secondary-text">{node.provider}</dd></div> : null}{typeof node.durationMs === 'number' ? <div className="flex justify-between gap-3"><dt className="text-muted-text">耗时</dt><dd className="text-secondary-text">{node.durationMs < 1000 ? `${node.durationMs} ms` : `${(node.durationMs / 1000).toFixed(1)} s`}</dd></div> : null}</dl>{node.message ? <p className="rounded-md border border-subtle bg-surface-muted/45 p-2 text-xs leading-5 text-secondary-text">{node.message}</p> : null}{entries.length ? <div className="border-t border-subtle pt-2"><p className="mb-1.5 text-xs text-muted-text">元数据</p><div className="flex flex-wrap gap-1">{entries.map(([key, value]) => <span key={key} className="rounded border border-subtle px-1.5 py-0.5 text-[11px] text-secondary-text">{key}: {typeof value === 'object' ? JSON.stringify(value) : String(value)}</span>)}</div></div> : null}</div>;
}

function EventList({ events, selectedNodeId, onSelect }: { events: RunFlowEvent[]; selectedNodeId?: string; onSelect: (nodeId: string) => void }) {
  if (!events.length) return <p className="text-xs text-muted-text">未记录运行事件</p>;
  return <div className="max-h-52 space-y-1.5 overflow-y-auto pr-1">{events.map((event) => <button key={event.id} type="button" disabled={!event.nodeId} onClick={() => event.nodeId && onSelect(event.nodeId)} className={`w-full rounded-md border px-2.5 py-2 text-left text-xs ${event.nodeId === selectedNodeId ? 'border-primary/50 bg-primary/10' : 'border-subtle bg-surface/60'} disabled:cursor-default`}><span className={`font-medium ${event.severity === 'danger' ? 'text-danger' : event.severity === 'warning' ? 'text-warning' : 'text-foreground'}`}>{event.title}</span>{event.message ? <span className="mt-1 block text-secondary-text">{event.message}</span> : null}</button>)}</div>;
}

export function RunFlowPanel({ recordId }: { recordId: number }) {
  const [flow, setFlow] = useState<RunFlowSnapshot | null>(null); const [error, setError] = useState(false); const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null); const [filter, setFilter] = useState<EventFilter>('all');
  useEffect(() => { let active = true; historyApi.getRunFlow(recordId).then((value) => { if (active) { setFlow(value); setSelectedNodeId(value.nodes[0]?.id || null); } }).catch(() => { if (active) setError(true); }); return () => { active = false; }; }, [recordId]);
  const selectedNode = useMemo(() => flow?.nodes.find((node) => node.id === selectedNodeId) || null, [flow, selectedNodeId]); const events = useMemo(() => flow?.events.filter((event) => filter === 'all' || event.severity === filter) || [], [filter, flow]);
  if (error) return null;
  if (!flow) return <section className="ui-card ui-card-bordered ui-card-padding-sm" aria-busy="true"><div className="flex items-center gap-2 text-sm text-secondary-text"><LoaderCircle className="h-4 w-4 animate-spin" />加载运行流...</div></section>;
  return <section className="ui-card ui-card-bordered ui-card-padding-sm text-left" aria-label="运行流"><div className="mb-3 flex flex-wrap items-start justify-between gap-3 border-b border-subtle pb-3"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-primary" aria-hidden="true" /><div><p className="text-sm font-semibold text-foreground">运行流回放</p><p className="text-xs text-secondary-text">{flow.traceId ? `Trace: ${flow.traceId}` : '旧报告未记录 Trace'}</p></div></div><Badge variant={STATUS[flow.status].badge}>{STATUS[flow.status].label}</Badge></div><div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_15rem]"><div className="space-y-3">{flow.lanes.slice().sort((a, b) => a.order - b.order).map((lane) => { const nodes = flow.nodes.filter((node) => node.lane === lane.id); return <div key={lane.id} className="relative border-l border-subtle pl-3"><p className="mb-2 text-xs font-medium text-secondary-text">{lane.label}</p><div className="grid gap-1.5 sm:grid-cols-2">{nodes.length ? nodes.map((node) => <FlowNode key={node.id} node={node} selected={node.id === selectedNodeId} onSelect={(value) => setSelectedNodeId(value.id)} />) : <p className="text-xs text-muted-text">未记录节点</p>}</div></div>; })}</div><aside className="rounded-lg border border-subtle bg-surface-muted/30 p-3"><p className="mb-2 text-xs font-medium text-secondary-text">节点详情</p><NodeDetails node={selectedNode} /></aside></div><div className="mt-4 border-t border-subtle pt-3"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-1.5 text-xs font-medium text-secondary-text"><Clock3 className="h-3.5 w-3.5" />运行事件</div><div className="flex gap-1">{EVENT_FILTERS.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded border px-2 py-0.5 text-xs ${filter === item ? 'border-primary/50 bg-primary/10 text-primary' : 'border-subtle text-secondary-text'}`}>{item === 'all' ? '全部' : item === 'warning' ? '告警' : '失败'}</button>)}</div></div><EventList events={events} selectedNodeId={selectedNodeId || undefined} onSelect={setSelectedNodeId} /></div></section>;
}
