"""initial_schema

Revision ID: b0bc3c721ef0
Revises:
Create Date: 2026-05-19 07:48:03.027933+00:00

引入 Alembic 时的全量初始 schema，由 autogenerate 对空库生成。
包含 32 张表，分为以下域：

  Alert     : alert_notifications, alert_rules, alert_triggers
  Core      : analysis_history, fundamental_snapshot, news_intel, stock_daily
  Conv/LLM  : conversation_messages, llm_usage
  Backtest  : backtest_results, backtest_summaries
  Portfolio : portfolio_accounts, portfolio_cash_ledger,
              portfolio_corporate_actions, portfolio_daily_snapshots,
              portfolio_fx_rates, portfolio_position_lots,
              portfolio_positions, portfolio_trades
  App (ToC) : app_audit_logs, app_growth_events, app_invoices,
              app_notices, app_orders, app_payment_events, app_plan_reminders,
              app_plans, app_reconciliation_diffs, app_reconciliation_reports,
              app_redeem_codes, app_refunds, app_subscriptions, app_user_byok_credentials,
              app_user_consents, app_user_email_verifications,
              app_user_notification_prefs, app_user_sessions,
              app_user_usage_counters, app_user_watchlists, app_users

存量库升级（首次引入 Alembic）：alembic stamp b0bc3c721ef0
新库部署：alembic upgrade head
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0bc3c721ef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ------------------------------------------------------------------ Alert
    op.create_table('alert_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('diagnostics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_notification_trigger_channel', 'alert_notifications', ['trigger_id', 'channel'], unique=False)
    op.create_index(op.f('ix_alert_notifications_channel'), 'alert_notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_alert_notifications_created_at'), 'alert_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_notifications_success'), 'alert_notifications', ['success'], unique=False)
    op.create_index(op.f('ix_alert_notifications_trigger_id'), 'alert_notifications', ['trigger_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('target_scope', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('cooldown_policy', sa.Text(), nullable=True),
    sa.Column('notification_policy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rule_type_target', 'alert_rules', ['alert_type', 'target'], unique=False)
    op.create_index('ix_alert_rule_user_id', 'alert_rules', ['user_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_alert_type'), 'alert_rules', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_created_at'), 'alert_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_rules_enabled'), 'alert_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_alert_rules_severity'), 'alert_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_alert_rules_source'), 'alert_rules', ['source'], unique=False)
    op.create_index(op.f('ix_alert_rules_target'), 'alert_rules', ['target'], unique=False)
    op.create_index(op.f('ix_alert_rules_target_scope'), 'alert_rules', ['target_scope'], unique=False)
    op.create_index(op.f('ix_alert_rules_updated_at'), 'alert_rules', ['updated_at'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('alert_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=64), nullable=True),
    sa.Column('data_timestamp', sa.DateTime(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('diagnostics', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_trigger_rule_time', 'alert_triggers', ['rule_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_triggers_data_timestamp'), 'alert_triggers', ['data_timestamp'], unique=False)
    op.create_index(op.f('ix_alert_triggers_rule_id'), 'alert_triggers', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_triggers_status'), 'alert_triggers', ['status'], unique=False)
    op.create_index(op.f('ix_alert_triggers_target'), 'alert_triggers', ['target'], unique=False)
    op.create_index(op.f('ix_alert_triggers_triggered_at'), 'alert_triggers', ['triggered_at'], unique=False)
    # ----------------------------------------------------------- Core Analysis
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('report_type', sa.String(length=16), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('operation_advice', sa.String(length=20), nullable=True),
    sa.Column('trend_prediction', sa.String(length=50), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('raw_result', sa.Text(), nullable=True),
    sa.Column('news_content', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('ideal_buy', sa.Float(), nullable=True),
    sa.Column('secondary_buy', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_code_time', 'analysis_history', ['code', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_history_code'), 'analysis_history', ['code'], unique=False)
    op.create_index(op.f('ix_analysis_history_created_at'), 'analysis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_history_query_id'), 'analysis_history', ['query_id'], unique=False)
    op.create_index(op.f('ix_analysis_history_report_type'), 'analysis_history', ['report_type'], unique=False)
    op.create_index(op.f('ix_analysis_history_user_id'), 'analysis_history', ['user_id'], unique=False)
    # --------------------------------- App (ToC): base tables, no FK dependency
    op.create_table('app_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_ref', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_audit_logs_action'), 'app_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_app_audit_logs_admin_id'), 'app_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_app_audit_logs_created_at'), 'app_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_audit_logs_target_user_id'), 'app_audit_logs', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_app_audit_logs_user_id'), 'app_audit_logs', ['user_id'], unique=False)
    op.create_table('app_payment_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_index(op.f('ix_app_payment_events_order_no'), 'app_payment_events', ['order_no'], unique=False)
    op.create_index(op.f('ix_app_payment_events_provider'), 'app_payment_events', ['provider'], unique=False)
    op.create_table('app_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('daily_analysis_limit', sa.Integer(), nullable=False),
    sa.Column('daily_agent_limit', sa.Integer(), nullable=False),
    sa.Column('max_stocks', sa.Integer(), nullable=False),
    sa.Column('allowed_models', sa.Text(), nullable=True),
    sa.Column('can_byok', sa.Boolean(), nullable=False),
    sa.Column('can_webhook', sa.Boolean(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_plans_code'), 'app_plans', ['code'], unique=True)
    op.create_index(op.f('ix_app_plans_is_active'), 'app_plans', ['is_active'], unique=False)
    op.create_table('app_reconciliation_diffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reconcile_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('diff_type', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=True),
    sa.Column('provider_trade_no', sa.String(length=64), nullable=True),
    sa.Column('local_amount_cents', sa.Integer(), nullable=True),
    sa.Column('channel_amount_cents', sa.Integer(), nullable=True),
    sa.Column('local_status', sa.String(length=24), nullable=True),
    sa.Column('channel_status', sa.String(length=24), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_reconciliation_diffs_diff_type'), 'app_reconciliation_diffs', ['diff_type'], unique=False)
    op.create_index(op.f('ix_app_reconciliation_diffs_order_no'), 'app_reconciliation_diffs', ['order_no'], unique=False)
    op.create_index(op.f('ix_app_reconciliation_diffs_provider'), 'app_reconciliation_diffs', ['provider'], unique=False)
    op.create_index(op.f('ix_app_reconciliation_diffs_provider_trade_no'), 'app_reconciliation_diffs', ['provider_trade_no'], unique=False)
    op.create_index(op.f('ix_app_reconciliation_diffs_reconcile_date'), 'app_reconciliation_diffs', ['reconcile_date'], unique=False)
    op.create_index(op.f('ix_app_reconciliation_diffs_resolved'), 'app_reconciliation_diffs', ['resolved'], unique=False)
    op.create_table('app_reconciliation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reconcile_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_channel', sa.Integer(), nullable=False),
    sa.Column('total_local', sa.Integer(), nullable=False),
    sa.Column('diff_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconcile_date', 'provider', name='uix_app_recon_report_date_provider')
    )
    op.create_index(op.f('ix_app_reconciliation_reports_provider'), 'app_reconciliation_reports', ['provider'], unique=False)
    op.create_index(op.f('ix_app_reconciliation_reports_reconcile_date'), 'app_reconciliation_reports', ['reconcile_date'], unique=False)
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('terms_version', sa.String(length=32), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_created_at'), 'app_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_users_deletion_requested_at'), 'app_users', ['deletion_requested_at'], unique=False)
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_is_admin'), 'app_users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_app_users_plan_code'), 'app_users', ['plan_code'], unique=False)
    op.create_index(op.f('ix_app_users_status'), 'app_users', ['status'], unique=False)
    # --------------------------------------------------------------- Backtest
    op.create_table('backtest_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('eval_window_days', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('total_evaluations', sa.Integer(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('insufficient_count', sa.Integer(), nullable=True),
    sa.Column('long_count', sa.Integer(), nullable=True),
    sa.Column('cash_count', sa.Integer(), nullable=True),
    sa.Column('win_count', sa.Integer(), nullable=True),
    sa.Column('loss_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('direction_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('win_rate_pct', sa.Float(), nullable=True),
    sa.Column('neutral_rate_pct', sa.Float(), nullable=True),
    sa.Column('avg_stock_return_pct', sa.Float(), nullable=True),
    sa.Column('avg_simulated_return_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_trigger_rate', sa.Float(), nullable=True),
    sa.Column('take_profit_trigger_rate', sa.Float(), nullable=True),
    sa.Column('ambiguous_rate', sa.Float(), nullable=True),
    sa.Column('avg_days_to_first_hit', sa.Float(), nullable=True),
    sa.Column('advice_breakdown_json', sa.Text(), nullable=True),
    sa.Column('diagnostics_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'code', 'eval_window_days', 'engine_version', name='uix_backtest_summary_scope_code_window_version')
    )
    op.create_index(op.f('ix_backtest_summaries_code'), 'backtest_summaries', ['code'], unique=False)
    op.create_index(op.f('ix_backtest_summaries_computed_at'), 'backtest_summaries', ['computed_at'], unique=False)
    op.create_index(op.f('ix_backtest_summaries_scope'), 'backtest_summaries', ['scope'], unique=False)
    # --------------------------------------------------------- Conversation/LLM
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_table('fundamental_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('source_chain', sa.Text(), nullable=True),
    sa.Column('coverage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_snapshot_code'), 'fundamental_snapshot', ['code'], unique=False)
    op.create_index('ix_fundamental_snapshot_created', 'fundamental_snapshot', ['created_at'], unique=False)
    op.create_index(op.f('ix_fundamental_snapshot_created_at'), 'fundamental_snapshot', ['created_at'], unique=False)
    op.create_index('ix_fundamental_snapshot_query_code', 'fundamental_snapshot', ['query_id', 'code'], unique=False)
    op.create_index(op.f('ix_fundamental_snapshot_query_id'), 'fundamental_snapshot', ['query_id'], unique=False)
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('stock_code', sa.String(length=16), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_call_type'), 'llm_usage', ['call_type'], unique=False)
    op.create_index(op.f('ix_llm_usage_called_at'), 'llm_usage', ['called_at'], unique=False)
    # -------------------------------------------------- Core: market data/news
    op.create_table('news_intel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('dimension', sa.String(length=32), nullable=True),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=768), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('query_source', sa.String(length=32), nullable=True),
    sa.Column('requester_platform', sa.String(length=20), nullable=True),
    sa.Column('requester_user_id', sa.String(length=64), nullable=True),
    sa.Column('requester_user_name', sa.String(length=64), nullable=True),
    sa.Column('requester_chat_id', sa.String(length=64), nullable=True),
    sa.Column('requester_message_id', sa.String(length=64), nullable=True),
    sa.Column('requester_query', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uix_news_url')
    )
    op.create_index('ix_news_code_pub', 'news_intel', ['code', 'published_date'], unique=False)
    op.create_index(op.f('ix_news_intel_code'), 'news_intel', ['code'], unique=False)
    op.create_index(op.f('ix_news_intel_dimension'), 'news_intel', ['dimension'], unique=False)
    op.create_index(op.f('ix_news_intel_fetched_at'), 'news_intel', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_news_intel_provider'), 'news_intel', ['provider'], unique=False)
    op.create_index(op.f('ix_news_intel_published_date'), 'news_intel', ['published_date'], unique=False)
    op.create_index(op.f('ix_news_intel_query_id'), 'news_intel', ['query_id'], unique=False)
    op.create_index(op.f('ix_news_intel_query_source'), 'news_intel', ['query_source'], unique=False)
    # ----------------------------------------------- Portfolio: base tables
    op.create_table('portfolio_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_account_owner_active', 'portfolio_accounts', ['owner_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_portfolio_accounts_created_at'), 'portfolio_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_accounts_is_active'), 'portfolio_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_portfolio_accounts_market'), 'portfolio_accounts', ['market'], unique=False)
    op.create_index(op.f('ix_portfolio_accounts_owner_id'), 'portfolio_accounts', ['owner_id'], unique=False)
    op.create_table('portfolio_fx_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.String(length=8), nullable=False),
    sa.Column('to_currency', sa.String(length=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_date', name='uix_portfolio_fx_pair_date')
    )
    op.create_index(op.f('ix_portfolio_fx_rates_from_currency'), 'portfolio_fx_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_portfolio_fx_rates_rate_date'), 'portfolio_fx_rates', ['rate_date'], unique=False)
    op.create_index(op.f('ix_portfolio_fx_rates_to_currency'), 'portfolio_fx_rates', ['to_currency'], unique=False)
    op.create_table('stock_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('ma5', sa.Float(), nullable=True),
    sa.Column('ma10', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'date', name='uix_code_date')
    )
    op.create_index('ix_code_date', 'stock_daily', ['code', 'date'], unique=False)
    op.create_index(op.f('ix_stock_daily_code'), 'stock_daily', ['code'], unique=False)
    op.create_index(op.f('ix_stock_daily_date'), 'stock_daily', ['date'], unique=False)
    # ----------------------- App (ToC): tables with FK to app_users (Phase 1+)
    op.create_table('app_growth_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('props', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_growth_events_event'), 'app_growth_events', ['event'], unique=False)
    op.create_index(op.f('ix_app_growth_events_session_id'), 'app_growth_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_app_growth_events_ts'), 'app_growth_events', ['ts'], unique=False)
    op.create_index(op.f('ix_app_growth_events_user_id'), 'app_growth_events', ['user_id'], unique=False)
    op.create_table('app_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('invoice_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_url', sa.String(length=1024), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_invoices_invoice_no'), 'app_invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_app_invoices_order_no'), 'app_invoices', ['order_no'], unique=False)
    op.create_index(op.f('ix_app_invoices_status'), 'app_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_app_invoices_user_id'), 'app_invoices', ['user_id'], unique=False)
    op.create_table('app_notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notice_type', sa.String(length=16), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('target_plan', sa.String(length=32), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notices_is_published'), 'app_notices', ['is_published'], unique=False)
    op.create_index('ix_app_notices_published_pinned', 'app_notices', ['is_published', 'is_pinned'], unique=False)
    op.create_table('app_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('grant_days', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('original_amount_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_trade_no', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('quote_snapshot', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_trade_no')
    )
    op.create_index(op.f('ix_app_orders_order_no'), 'app_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_app_orders_plan_code'), 'app_orders', ['plan_code'], unique=False)
    op.create_index('ix_app_orders_provider_status', 'app_orders', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_app_orders_status'), 'app_orders', ['status'], unique=False)
    op.create_index('ix_app_orders_user_created', 'app_orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_app_orders_user_id'), 'app_orders', ['user_id'], unique=False)
    op.create_table('app_plan_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('reminder_type', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_code', 'expires_at', 'reminder_type', name='uix_app_plan_reminders_user_plan_expires_type')
    )
    op.create_index(op.f('ix_app_plan_reminders_expires_at'), 'app_plan_reminders', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_plan_reminders_plan_code'), 'app_plan_reminders', ['plan_code'], unique=False)
    op.create_index(op.f('ix_app_plan_reminders_reminder_type'), 'app_plan_reminders', ['reminder_type'], unique=False)
    op.create_index(op.f('ix_app_plan_reminders_sent_at'), 'app_plan_reminders', ['sent_at'], unique=False)
    op.create_index(op.f('ix_app_plan_reminders_user_id'), 'app_plan_reminders', ['user_id'], unique=False)
    op.create_table('app_redeem_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('grant_days', sa.Integer(), nullable=False),
    sa.Column('redeemed_by', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['redeemed_by'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_redeem_codes_code'), 'app_redeem_codes', ['code'], unique=True)
    op.create_index(op.f('ix_app_redeem_codes_expires_at'), 'app_redeem_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_redeem_codes_plan_code'), 'app_redeem_codes', ['plan_code'], unique=False)
    op.create_index(op.f('ix_app_redeem_codes_redeemed_at'), 'app_redeem_codes', ['redeemed_at'], unique=False)
    op.create_index(op.f('ix_app_redeem_codes_redeemed_by'), 'app_redeem_codes', ['redeemed_by'], unique=False)
    op.create_table('app_refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refund_no', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_refund_no', sa.String(length=64), nullable=True),
    sa.Column('revoke_subscription', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_refunds_order_no'), 'app_refunds', ['order_no'], unique=False)
    op.create_index(op.f('ix_app_refunds_refund_no'), 'app_refunds', ['refund_no'], unique=True)
    op.create_index(op.f('ix_app_refunds_status'), 'app_refunds', ['status'], unique=False)
    op.create_index(op.f('ix_app_refunds_user_id'), 'app_refunds', ['user_id'], unique=False)
    op.create_table('app_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_subscriptions_expires_at'), 'app_subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_subscriptions_plan_code'), 'app_subscriptions', ['plan_code'], unique=False)
    op.create_index(op.f('ix_app_subscriptions_source'), 'app_subscriptions', ['source'], unique=False)
    op.create_index(op.f('ix_app_subscriptions_started_at'), 'app_subscriptions', ['started_at'], unique=False)
    op.create_index(op.f('ix_app_subscriptions_user_id'), 'app_subscriptions', ['user_id'], unique=False)
    op.create_table('app_user_byok_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uix_app_user_byok_user_provider')
    )
    op.create_index(op.f('ix_app_user_byok_credentials_provider'), 'app_user_byok_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_app_user_byok_credentials_user_id'), 'app_user_byok_credentials', ['user_id'], unique=False)
    op.create_table('app_user_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terms_version', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('agreed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_consents_agreed_at'), 'app_user_consents', ['agreed_at'], unique=False)
    op.create_index(op.f('ix_app_user_consents_purpose'), 'app_user_consents', ['purpose'], unique=False)
    op.create_index(op.f('ix_app_user_consents_terms_version'), 'app_user_consents', ['terms_version'], unique=False)
    op.create_index(op.f('ix_app_user_consents_user_id'), 'app_user_consents', ['user_id'], unique=False)
    op.create_table('app_user_email_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email_verifications_created_at'), 'app_user_email_verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_user_email_verifications_expires_at'), 'app_user_email_verifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_user_email_verifications_purpose'), 'app_user_email_verifications', ['purpose'], unique=False)
    op.create_index(op.f('ix_app_user_email_verifications_token_hash'), 'app_user_email_verifications', ['token_hash'], unique=True)
    op.create_index(op.f('ix_app_user_email_verifications_user_id'), 'app_user_email_verifications', ['user_id'], unique=False)
    op.create_table('app_user_notification_prefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('webhook_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_notification_prefs_user_id'), 'app_user_notification_prefs', ['user_id'], unique=True)
    op.create_table('app_user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_sessions_expires_at'), 'app_user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_app_user_sessions_revoked_at'), 'app_user_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_app_user_sessions_token_hash'), 'app_user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_app_user_sessions_user_id'), 'app_user_sessions', ['user_id'], unique=False)
    op.create_table('app_user_usage_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('counter_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'counter_date', 'kind', name='uix_app_user_usage_user_date_kind')
    )
    op.create_index(op.f('ix_app_user_usage_counters_counter_date'), 'app_user_usage_counters', ['counter_date'], unique=False)
    op.create_index(op.f('ix_app_user_usage_counters_kind'), 'app_user_usage_counters', ['kind'], unique=False)
    op.create_index(op.f('ix_app_user_usage_counters_user_id'), 'app_user_usage_counters', ['user_id'], unique=False)
    op.create_table('app_user_watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=32), nullable=False),
    sa.Column('stock_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_code', name='uix_app_user_watchlist_user_code')
    )
    op.create_index(op.f('ix_app_user_watchlists_stock_code'), 'app_user_watchlists', ['stock_code'], unique=False)
    op.create_index(op.f('ix_app_user_watchlists_user_id'), 'app_user_watchlists', ['user_id'], unique=False)
    # --------------------------------- Backtest: per-record (FK -> analysis_history)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_history_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=True),
    sa.Column('eval_window_days', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('eval_status', sa.String(length=32), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('operation_advice', sa.String(length=20), nullable=True),
    sa.Column('position_recommendation', sa.String(length=8), nullable=True),
    sa.Column('start_price', sa.Float(), nullable=True),
    sa.Column('end_close', sa.Float(), nullable=True),
    sa.Column('max_high', sa.Float(), nullable=True),
    sa.Column('min_low', sa.Float(), nullable=True),
    sa.Column('stock_return_pct', sa.Float(), nullable=True),
    sa.Column('direction_expected', sa.String(length=16), nullable=True),
    sa.Column('direction_correct', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('hit_stop_loss', sa.Boolean(), nullable=True),
    sa.Column('hit_take_profit', sa.Boolean(), nullable=True),
    sa.Column('first_hit', sa.String(length=16), nullable=True),
    sa.Column('first_hit_date', sa.Date(), nullable=True),
    sa.Column('first_hit_trading_days', sa.Integer(), nullable=True),
    sa.Column('simulated_entry_price', sa.Float(), nullable=True),
    sa.Column('simulated_exit_price', sa.Float(), nullable=True),
    sa.Column('simulated_exit_reason', sa.String(length=24), nullable=True),
    sa.Column('simulated_return_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_history_id'], ['analysis_history.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_history_id', 'eval_window_days', 'engine_version', name='uix_backtest_analysis_window_version')
    )
    op.create_index('ix_backtest_code_date', 'backtest_results', ['code', 'analysis_date'], unique=False)
    op.create_index(op.f('ix_backtest_results_analysis_date'), 'backtest_results', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_backtest_results_analysis_history_id'), 'backtest_results', ['analysis_history_id'], unique=False)
    op.create_index(op.f('ix_backtest_results_code'), 'backtest_results', ['code'], unique=False)
    op.create_index(op.f('ix_backtest_results_evaluated_at'), 'backtest_results', ['evaluated_at'], unique=False)
    # ----------------------------- Portfolio: FK tables (FK -> portfolio_accounts)
    op.create_table('portfolio_cash_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_cash_account_date', 'portfolio_cash_ledger', ['account_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_portfolio_cash_ledger_account_id'), 'portfolio_cash_ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_cash_ledger_created_at'), 'portfolio_cash_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_cash_ledger_event_date'), 'portfolio_cash_ledger', ['event_date'], unique=False)
    op.create_table('portfolio_corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=24), nullable=False),
    sa.Column('cash_dividend_per_share', sa.Float(), nullable=True),
    sa.Column('split_ratio', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_ca_account_date', 'portfolio_corporate_actions', ['account_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_portfolio_corporate_actions_account_id'), 'portfolio_corporate_actions', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_corporate_actions_created_at'), 'portfolio_corporate_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_corporate_actions_effective_date'), 'portfolio_corporate_actions', ['effective_date'], unique=False)
    op.create_index(op.f('ix_portfolio_corporate_actions_symbol'), 'portfolio_corporate_actions', ['symbol'], unique=False)
    op.create_table('portfolio_daily_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cost_method', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('total_cash', sa.Float(), nullable=False),
    sa.Column('total_market_value', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('fee_total', sa.Float(), nullable=False),
    sa.Column('tax_total', sa.Float(), nullable=False),
    sa.Column('fx_stale', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date', 'cost_method', name='uix_portfolio_snapshot_account_date_method')
    )
    op.create_index(op.f('ix_portfolio_daily_snapshots_account_id'), 'portfolio_daily_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_daily_snapshots_created_at'), 'portfolio_daily_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_daily_snapshots_snapshot_date'), 'portfolio_daily_snapshots', ['snapshot_date'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cost_method', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('market_value_base', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_base', sa.Float(), nullable=False),
    sa.Column('valuation_currency', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', 'market', 'currency', 'cost_method', name='uix_portfolio_position_account_symbol_market_currency')
    )
    op.create_index(op.f('ix_portfolio_positions_account_id'), 'portfolio_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_positions_symbol'), 'portfolio_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_positions_updated_at'), 'portfolio_positions', ['updated_at'], unique=False)
    op.create_table('portfolio_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('trade_uid', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'dedup_hash', name='uix_portfolio_trade_dedup_hash'),
    sa.UniqueConstraint('account_id', 'trade_uid', name='uix_portfolio_trade_uid')
    )
    op.create_index('ix_portfolio_trade_account_date', 'portfolio_trades', ['account_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_account_id'), 'portfolio_trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_created_at'), 'portfolio_trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_dedup_hash'), 'portfolio_trades', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_symbol'), 'portfolio_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_trades_trade_date'), 'portfolio_trades', ['trade_date'], unique=False)
    op.create_table('portfolio_position_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cost_method', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('remaining_quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('source_trade_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['portfolio_accounts.id'], ),
    sa.ForeignKeyConstraint(['source_trade_id'], ['portfolio_trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_lot_account_symbol', 'portfolio_position_lots', ['account_id', 'symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_position_lots_account_id'), 'portfolio_position_lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_position_lots_open_date'), 'portfolio_position_lots', ['open_date'], unique=False)
    op.create_index(op.f('ix_portfolio_position_lots_symbol'), 'portfolio_position_lots', ['symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_position_lots_updated_at'), 'portfolio_position_lots', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop order is reverse FK dependency.

    # ----------------------------- Portfolio: FK tables (FK -> portfolio_accounts)
    op.drop_index(op.f('ix_portfolio_position_lots_updated_at'), table_name='portfolio_position_lots')
    op.drop_index(op.f('ix_portfolio_position_lots_symbol'), table_name='portfolio_position_lots')
    op.drop_index(op.f('ix_portfolio_position_lots_open_date'), table_name='portfolio_position_lots')
    op.drop_index(op.f('ix_portfolio_position_lots_account_id'), table_name='portfolio_position_lots')
    op.drop_index('ix_portfolio_lot_account_symbol', table_name='portfolio_position_lots')
    op.drop_table('portfolio_position_lots')
    op.drop_index(op.f('ix_portfolio_trades_trade_date'), table_name='portfolio_trades')
    op.drop_index(op.f('ix_portfolio_trades_symbol'), table_name='portfolio_trades')
    op.drop_index(op.f('ix_portfolio_trades_dedup_hash'), table_name='portfolio_trades')
    op.drop_index(op.f('ix_portfolio_trades_created_at'), table_name='portfolio_trades')
    op.drop_index(op.f('ix_portfolio_trades_account_id'), table_name='portfolio_trades')
    op.drop_index('ix_portfolio_trade_account_date', table_name='portfolio_trades')
    op.drop_table('portfolio_trades')
    op.drop_index(op.f('ix_portfolio_positions_updated_at'), table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_symbol'), table_name='portfolio_positions')
    op.drop_index(op.f('ix_portfolio_positions_account_id'), table_name='portfolio_positions')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_portfolio_daily_snapshots_snapshot_date'), table_name='portfolio_daily_snapshots')
    op.drop_index(op.f('ix_portfolio_daily_snapshots_created_at'), table_name='portfolio_daily_snapshots')
    op.drop_index(op.f('ix_portfolio_daily_snapshots_account_id'), table_name='portfolio_daily_snapshots')
    op.drop_table('portfolio_daily_snapshots')
    op.drop_index(op.f('ix_portfolio_corporate_actions_symbol'), table_name='portfolio_corporate_actions')
    op.drop_index(op.f('ix_portfolio_corporate_actions_effective_date'), table_name='portfolio_corporate_actions')
    op.drop_index(op.f('ix_portfolio_corporate_actions_created_at'), table_name='portfolio_corporate_actions')
    op.drop_index(op.f('ix_portfolio_corporate_actions_account_id'), table_name='portfolio_corporate_actions')
    op.drop_index('ix_portfolio_ca_account_date', table_name='portfolio_corporate_actions')
    op.drop_table('portfolio_corporate_actions')
    op.drop_index(op.f('ix_portfolio_cash_ledger_event_date'), table_name='portfolio_cash_ledger')
    op.drop_index(op.f('ix_portfolio_cash_ledger_created_at'), table_name='portfolio_cash_ledger')
    op.drop_index(op.f('ix_portfolio_cash_ledger_account_id'), table_name='portfolio_cash_ledger')
    op.drop_index('ix_portfolio_cash_account_date', table_name='portfolio_cash_ledger')
    op.drop_table('portfolio_cash_ledger')
    # --------------------------------- Backtest: per-record (FK -> analysis_history)
    op.drop_index(op.f('ix_backtest_results_evaluated_at'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_code'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_analysis_history_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_analysis_date'), table_name='backtest_results')
    op.drop_index('ix_backtest_code_date', table_name='backtest_results')
    op.drop_table('backtest_results')
    # ----------------------- App (ToC): tables with FK to app_users
    op.drop_index(op.f('ix_app_user_watchlists_user_id'), table_name='app_user_watchlists')
    op.drop_index(op.f('ix_app_user_watchlists_stock_code'), table_name='app_user_watchlists')
    op.drop_table('app_user_watchlists')
    op.drop_index(op.f('ix_app_user_usage_counters_user_id'), table_name='app_user_usage_counters')
    op.drop_index(op.f('ix_app_user_usage_counters_kind'), table_name='app_user_usage_counters')
    op.drop_index(op.f('ix_app_user_usage_counters_counter_date'), table_name='app_user_usage_counters')
    op.drop_table('app_user_usage_counters')
    op.drop_index(op.f('ix_app_user_sessions_user_id'), table_name='app_user_sessions')
    op.drop_index(op.f('ix_app_user_sessions_token_hash'), table_name='app_user_sessions')
    op.drop_index(op.f('ix_app_user_sessions_revoked_at'), table_name='app_user_sessions')
    op.drop_index(op.f('ix_app_user_sessions_expires_at'), table_name='app_user_sessions')
    op.drop_table('app_user_sessions')
    op.drop_index(op.f('ix_app_user_notification_prefs_user_id'), table_name='app_user_notification_prefs')
    op.drop_table('app_user_notification_prefs')
    op.drop_index(op.f('ix_app_user_email_verifications_user_id'), table_name='app_user_email_verifications')
    op.drop_index(op.f('ix_app_user_email_verifications_token_hash'), table_name='app_user_email_verifications')
    op.drop_index(op.f('ix_app_user_email_verifications_purpose'), table_name='app_user_email_verifications')
    op.drop_index(op.f('ix_app_user_email_verifications_expires_at'), table_name='app_user_email_verifications')
    op.drop_index(op.f('ix_app_user_email_verifications_created_at'), table_name='app_user_email_verifications')
    op.drop_table('app_user_email_verifications')
    op.drop_index(op.f('ix_app_user_consents_user_id'), table_name='app_user_consents')
    op.drop_index(op.f('ix_app_user_consents_terms_version'), table_name='app_user_consents')
    op.drop_index(op.f('ix_app_user_consents_purpose'), table_name='app_user_consents')
    op.drop_index(op.f('ix_app_user_consents_agreed_at'), table_name='app_user_consents')
    op.drop_table('app_user_consents')
    op.drop_index(op.f('ix_app_user_byok_credentials_user_id'), table_name='app_user_byok_credentials')
    op.drop_index(op.f('ix_app_user_byok_credentials_provider'), table_name='app_user_byok_credentials')
    op.drop_table('app_user_byok_credentials')
    op.drop_index(op.f('ix_app_subscriptions_user_id'), table_name='app_subscriptions')
    op.drop_index(op.f('ix_app_subscriptions_started_at'), table_name='app_subscriptions')
    op.drop_index(op.f('ix_app_subscriptions_source'), table_name='app_subscriptions')
    op.drop_index(op.f('ix_app_subscriptions_plan_code'), table_name='app_subscriptions')
    op.drop_index(op.f('ix_app_subscriptions_expires_at'), table_name='app_subscriptions')
    op.drop_table('app_subscriptions')
    op.drop_index(op.f('ix_app_refunds_user_id'), table_name='app_refunds')
    op.drop_index(op.f('ix_app_refunds_status'), table_name='app_refunds')
    op.drop_index(op.f('ix_app_refunds_refund_no'), table_name='app_refunds')
    op.drop_index(op.f('ix_app_refunds_order_no'), table_name='app_refunds')
    op.drop_table('app_refunds')
    op.drop_index(op.f('ix_app_redeem_codes_redeemed_by'), table_name='app_redeem_codes')
    op.drop_index(op.f('ix_app_redeem_codes_redeemed_at'), table_name='app_redeem_codes')
    op.drop_index(op.f('ix_app_redeem_codes_plan_code'), table_name='app_redeem_codes')
    op.drop_index(op.f('ix_app_redeem_codes_expires_at'), table_name='app_redeem_codes')
    op.drop_index(op.f('ix_app_redeem_codes_code'), table_name='app_redeem_codes')
    op.drop_table('app_redeem_codes')
    op.drop_index(op.f('ix_app_plan_reminders_user_id'), table_name='app_plan_reminders')
    op.drop_index(op.f('ix_app_plan_reminders_sent_at'), table_name='app_plan_reminders')
    op.drop_index(op.f('ix_app_plan_reminders_reminder_type'), table_name='app_plan_reminders')
    op.drop_index(op.f('ix_app_plan_reminders_plan_code'), table_name='app_plan_reminders')
    op.drop_index(op.f('ix_app_plan_reminders_expires_at'), table_name='app_plan_reminders')
    op.drop_table('app_plan_reminders')
    op.drop_index(op.f('ix_app_orders_user_id'), table_name='app_orders')
    op.drop_index('ix_app_orders_user_created', table_name='app_orders')
    op.drop_index(op.f('ix_app_orders_status'), table_name='app_orders')
    op.drop_index('ix_app_orders_provider_status', table_name='app_orders')
    op.drop_index(op.f('ix_app_orders_plan_code'), table_name='app_orders')
    op.drop_index(op.f('ix_app_orders_order_no'), table_name='app_orders')
    op.drop_table('app_orders')
    op.drop_index('ix_app_notices_published_pinned', table_name='app_notices')
    op.drop_index(op.f('ix_app_notices_is_published'), table_name='app_notices')
    op.drop_table('app_notices')
    op.drop_index(op.f('ix_app_invoices_user_id'), table_name='app_invoices')
    op.drop_index(op.f('ix_app_invoices_status'), table_name='app_invoices')
    op.drop_index(op.f('ix_app_invoices_order_no'), table_name='app_invoices')
    op.drop_index(op.f('ix_app_invoices_invoice_no'), table_name='app_invoices')
    op.drop_table('app_invoices')
    op.drop_index(op.f('ix_app_growth_events_user_id'), table_name='app_growth_events')
    op.drop_index(op.f('ix_app_growth_events_ts'), table_name='app_growth_events')
    op.drop_index(op.f('ix_app_growth_events_session_id'), table_name='app_growth_events')
    op.drop_index(op.f('ix_app_growth_events_event'), table_name='app_growth_events')
    op.drop_table('app_growth_events')
    # -------------------------------------------------- Core: market data/news
    op.drop_index(op.f('ix_stock_daily_date'), table_name='stock_daily')
    op.drop_index(op.f('ix_stock_daily_code'), table_name='stock_daily')
    op.drop_index('ix_code_date', table_name='stock_daily')
    op.drop_table('stock_daily')
    # ----------------------------------------------- Portfolio: base tables
    op.drop_index(op.f('ix_portfolio_fx_rates_to_currency'), table_name='portfolio_fx_rates')
    op.drop_index(op.f('ix_portfolio_fx_rates_rate_date'), table_name='portfolio_fx_rates')
    op.drop_index(op.f('ix_portfolio_fx_rates_from_currency'), table_name='portfolio_fx_rates')
    op.drop_table('portfolio_fx_rates')
    op.drop_index(op.f('ix_portfolio_accounts_owner_id'), table_name='portfolio_accounts')
    op.drop_index(op.f('ix_portfolio_accounts_market'), table_name='portfolio_accounts')
    op.drop_index(op.f('ix_portfolio_accounts_is_active'), table_name='portfolio_accounts')
    op.drop_index(op.f('ix_portfolio_accounts_created_at'), table_name='portfolio_accounts')
    op.drop_index('ix_portfolio_account_owner_active', table_name='portfolio_accounts')
    op.drop_table('portfolio_accounts')
    op.drop_index(op.f('ix_news_intel_query_source'), table_name='news_intel')
    op.drop_index(op.f('ix_news_intel_query_id'), table_name='news_intel')
    op.drop_index(op.f('ix_news_intel_published_date'), table_name='news_intel')
    op.drop_index(op.f('ix_news_intel_provider'), table_name='news_intel')
    op.drop_index(op.f('ix_news_intel_fetched_at'), table_name='news_intel')
    op.drop_index(op.f('ix_news_intel_dimension'), table_name='news_intel')
    op.drop_index(op.f('ix_news_intel_code'), table_name='news_intel')
    op.drop_index('ix_news_code_pub', table_name='news_intel')
    op.drop_table('news_intel')
    # --------------------------------------------------------- Conversation/LLM
    op.drop_index(op.f('ix_llm_usage_called_at'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_call_type'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index(op.f('ix_fundamental_snapshot_query_id'), table_name='fundamental_snapshot')
    op.drop_index('ix_fundamental_snapshot_query_code', table_name='fundamental_snapshot')
    op.drop_index(op.f('ix_fundamental_snapshot_created_at'), table_name='fundamental_snapshot')
    op.drop_index('ix_fundamental_snapshot_created', table_name='fundamental_snapshot')
    op.drop_index(op.f('ix_fundamental_snapshot_code'), table_name='fundamental_snapshot')
    op.drop_table('fundamental_snapshot')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # --------------------------------------------------------------- Backtest
    op.drop_index(op.f('ix_backtest_summaries_scope'), table_name='backtest_summaries')
    op.drop_index(op.f('ix_backtest_summaries_computed_at'), table_name='backtest_summaries')
    op.drop_index(op.f('ix_backtest_summaries_code'), table_name='backtest_summaries')
    op.drop_table('backtest_summaries')
    # --------------------------------- App (ToC): base tables, no FK dependency
    op.drop_index(op.f('ix_app_users_status'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_plan_code'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_is_admin'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_deletion_requested_at'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_created_at'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index(op.f('ix_app_reconciliation_reports_reconcile_date'), table_name='app_reconciliation_reports')
    op.drop_index(op.f('ix_app_reconciliation_reports_provider'), table_name='app_reconciliation_reports')
    op.drop_table('app_reconciliation_reports')
    op.drop_index(op.f('ix_app_reconciliation_diffs_resolved'), table_name='app_reconciliation_diffs')
    op.drop_index(op.f('ix_app_reconciliation_diffs_reconcile_date'), table_name='app_reconciliation_diffs')
    op.drop_index(op.f('ix_app_reconciliation_diffs_provider_trade_no'), table_name='app_reconciliation_diffs')
    op.drop_index(op.f('ix_app_reconciliation_diffs_provider'), table_name='app_reconciliation_diffs')
    op.drop_index(op.f('ix_app_reconciliation_diffs_order_no'), table_name='app_reconciliation_diffs')
    op.drop_index(op.f('ix_app_reconciliation_diffs_diff_type'), table_name='app_reconciliation_diffs')
    op.drop_table('app_reconciliation_diffs')
    op.drop_index(op.f('ix_app_plans_is_active'), table_name='app_plans')
    op.drop_index(op.f('ix_app_plans_code'), table_name='app_plans')
    op.drop_table('app_plans')
    op.drop_index(op.f('ix_app_payment_events_provider'), table_name='app_payment_events')
    op.drop_index(op.f('ix_app_payment_events_order_no'), table_name='app_payment_events')
    op.drop_table('app_payment_events')
    op.drop_index(op.f('ix_app_audit_logs_user_id'), table_name='app_audit_logs')
    op.drop_index(op.f('ix_app_audit_logs_target_user_id'), table_name='app_audit_logs')
    op.drop_index(op.f('ix_app_audit_logs_created_at'), table_name='app_audit_logs')
    op.drop_index(op.f('ix_app_audit_logs_admin_id'), table_name='app_audit_logs')
    op.drop_index(op.f('ix_app_audit_logs_action'), table_name='app_audit_logs')
    op.drop_table('app_audit_logs')
    # ----------------------------------------------------------- Core Analysis
    op.drop_index(op.f('ix_analysis_history_user_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_report_type'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_query_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_created_at'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_code'), table_name='analysis_history')
    op.drop_index('ix_analysis_code_time', table_name='analysis_history')
    op.drop_table('analysis_history')
    # ------------------------------------------------------------------ Alert
    op.drop_index(op.f('ix_alert_triggers_triggered_at'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_target'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_status'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_rule_id'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_data_timestamp'), table_name='alert_triggers')
    op.drop_index('ix_alert_trigger_rule_time', table_name='alert_triggers')
    op.drop_table('alert_triggers')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_updated_at'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_target_scope'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_target'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_source'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_severity'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_enabled'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_created_at'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_alert_type'), table_name='alert_rules')
    op.drop_index('ix_alert_rule_user_id', table_name='alert_rules')
    op.drop_index('ix_alert_rule_type_target', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_notifications_trigger_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_success'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_created_at'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_channel'), table_name='alert_notifications')
    op.drop_index('ix_alert_notification_trigger_channel', table_name='alert_notifications')
    op.drop_table('alert_notifications')
    # ### end Alembic commands ###
